input_variables: [text, var]
template: 'Суммаризируй все части  в один текст.


"{text}"


Теперь перечисли продукты и услуги которые предлагает компания "{var}" сухим деловым тоном основываясь на фактах из текста.
Описание каждого продукта начинай с новой строки. Форма вывода: продукт или услуга - описание.
Не пиши описание компании, только о ее услугах и продуктах.
Не пропускай важные факты.  Не повторяй и не дублируй фразы. 
Не пиши про продукты или услуги других компаний.
'
template_format: f-string
_type: prompt

